### ISSUE TITLE
SPFx Solution scaffolding is failing

### ISSUE THREAD

**Issue by venkatkonjeti** [waldekmastykarz/docker-spfx#16]
I ran the script docker Run command as follows
`docker run -it --rm --name spfx-helloworld -v /C/"Docker Containers"/spfx-helloworld:/usr/app/spfx -p 5432:5432 -p 4321:4321 -p 35729:35729 waldekm/spfx`

It downloaded packages to node_modules -> .staging folder in chunk but the merging all these chunks and copying final modules to the node_modules folder gets failed and throws following error.

`npm ERR! code EINTEGRITY
npm ERR! sha512-WUyEExfSROSn5XIQudmVpo8cXV2h7RVvGDZTFIbWAEwh2gyxQjHegzoGDLeoTWy0ulD6+RM3vonrQNE5c629AQ== integrity checksum failed when using sha512: wanted sha512-WUyEExfSROSn5XIQudmVpo8cXV2h7RVvGDZTFIbWAEwh2gyxQjHegzoGDLeoTWy0ulD6+RM3vonrQNE5c629AQ== but got sha512-fgHk6vaSnfLEnMfr6yjjev2/BSs3KfGfnrPBJgVD8uKoFiCBQ99OxIWl1mERP6v0v542QS12qFnLZhMrkbCgtQ==. (6322813 bytes)`

Any help, please. 

Thanks.

**Comment by waldekmastykarz** [comment]
Are you using a custom .npmrc file by any chance or using the container as-is?

**Comment by venkatkonjeti** [comment]
I am using container as is.

**Comment by waldekmastykarz** [comment]
Like the error mentions, it seems to be related to npm. Which version of the container are you using? Can you still repro it?

**Comment by venkatkonjeti** [comment]
I was using waldekm/spfx:latest container version I am using. I tried multiple times and still having issue.

**Comment by waldekmastykarz** [comment]
Could you please check if you can reproduce this issue in a different version of the container?

**Comment by venkatkonjeti** [comment]
The docker image 1.4.1 is working is as expected.

With docker image 1.6 (latest) after scaffold I see there is one package left _office-ui-fabric-react-e0ecb022_ in the node_modules/.staging folder. I am suspecting this might be causing an issue.

**Comment by waldekmastykarz** [comment]
Interesting. Thanks for checking. Let me check if I can reproduce it

**Comment by shurick81** [comment]
If it is not replicated on the newer images, should we close the issue?
