### ISSUE TITLE
yo @microsoft/sharepoint giving me an error

### ISSUE THREAD

**Issue by akaradhey** [waldekmastykarz/docker-spfx#2]
warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
112664 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
112665 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
112665 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
112665 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
112665 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
112666 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@* (node_modules/@microsoft/gulp-core-build-webpack/node_modules/fsevents):
112667 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
112668 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
112668 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
112668 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
112668 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
112669 verbose stack Error: EPROTO: protocol error, symlink '../semver/bin/semver' -> '/usr/app/spfx/spfxAngularApp/node_modules/@microsoft/rush-lib/node_modules/.bin/semver'
112669 verbose stack     at Error (native)
112670 verbose cwd /usr/app/spfx/spfxAngularApp
112671 error Linux 4.4.52-boot2docker
112672 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--cache-min" "86400"
112673 error node v6.9.4
112674 error npm  v3.10.10
112675 error path ../semver/bin/semver
112676 error code EPROTO
112677 error errno -71
112678 error syscall symlink
112679 error EPROTO: protocol error, symlink '../semver/bin/semver' -> '/usr/app/spfx/spfxAngularApp/node_modules/@microsoft/rush-lib/node_modules/.bin/semver'

**Comment by waldekmastykarz** [comment]
Could you try again? Sometimes similar errors are caused by network issues.

**Comment by akaradhey** [comment]
No Still showing the same error.

**Comment by waldekmastykarz** [comment]
Unfortunately I am unable to reproduce this issue. I tried scaffolding a new project using no JS framework as well as React and both worked correctly.
What command are you using to run the container? How are you running Docker (i.e.. Docker for Windows, Docker for macOS, different)?

**Comment by akaradhey** [comment]
I am running docker using docker toolbox for windows 8.1. I am using the same command as mentioned in the read me:- docker run -h spfx -it --rm --name spfx-helloworld -v /c/projects/spfx-helloworld:/usr/app/spfx -p 5432:5432 -p 4321:4321 -p 35729:35729 waldekm/spfx

**Comment by waldekmastykarz** [comment]
Could you try adding the `--privileged` flag, like:

```
docker run -h spfx -it --rm --name spfx-helloworld -v /c/projects/spfx-helloworld:/usr/app/spfx -p 5432:5432 -p 4321:4321 -p 35729:35729 --privileged waldekm/spfx
```

**Comment by waldekmastykarz** [comment]
Closing due to lack of response
