### ISSUE TITLE
SPWebBuildRig.js workaround line-numbers have changed for 1.8.2

### ISSUE THREAD

**Issue by martinlingstuyl** [waldekmastykarz/docker-spfx#27]
Hi @waldekmastykarz,

In the readme you mention the workaround for which you need to change a few lines in the SPWebBuildRig.js file.

I blindly copy pasted your code to lines 83-85 (never wise :grimacing:), only to discover later that the linenumbers have changed. It's no longer 83-85, but 88-90 (using SPFx 1.8.2) that we have to change. Otherwise we're overruling the mergeConfig of the deployCdnPath.

I agree in advance, the problem here is primarily between the chair and the screen. But maybe you could, for completeness sake, update your readme accordingly? Maybe it would help for suckers like me who end up staring at a white screen and take unnecessary time retracing their steps. 

Thanks in advance :pensive:

**Comment by waldekmastykarz** [comment]
Good catch and sorry for the trouble 👍

**Comment by shurick81** [comment]
Is there anything you would recommend to do now regarding the issue or should we close it?

**Comment by waldekmastykarz** [comment]
I think we need to verify that the guidance is correct for v1.8.2.

**Comment by shurick81** [comment]
Valid point, I have done some research of the line numbers depending on the version:

- https://unpkg.com/@microsoft/sp-build-web@1.6.0/lib/SPWebBuildRig.js, lines 83-85
- https://unpkg.com/@microsoft/sp-build-web@1.7.0/lib/SPWebBuildRig.js, lines 83-85
- https://unpkg.com/@microsoft/sp-build-web@1.7.1/lib/SPWebBuildRig.js, lines 83-85
- https://unpkg.com/@microsoft/sp-build-web@1.8.0/lib/SPWebBuildRig.js, lines 88-90
- https://unpkg.com/@microsoft/sp-build-web@1.8.1/lib/SPWebBuildRig.js, lines 88-90
- https://unpkg.com/@microsoft/sp-build-web@1.8.2/lib/SPWebBuildRig.js, lines 88-90
- https://unpkg.com/@microsoft/sp-build-web@1.9.1/lib/SPWebBuildRig.js, lines 92-94
- https://unpkg.com/@microsoft/sp-build-web@1.10.0/lib/SPWebBuildRig.js, lines 96-98
- https://unpkg.com/@microsoft/sp-build-web@1.11.0/lib/SPWebBuildRig.js, lines 96-98

Should we specify the lines for each version in our guidance or should we just suggest searching the specific pattern?

**Comment by martinlingstuyl** [comment]
Wow, that's solid ❤️

**Comment by waldekmastykarz** [comment]
Awesome @shurick81 👏 Yes, offering guidance per version would be the best. Would you like to submit a PR based on your work?

**Comment by shurick81** [comment]
https://github.com/waldekmastykarz/docker-spfx/pull/62

**Comment by waldekmastykarz** [comment]
PR merged
