### ISSUE TITLE
***Manifest not found for componentId and Field Customizer

### ISSUE THREAD

**Issue by Sartor87** [waldekmastykarz/docker-spfx#33]
1. Created a hello world field customizer
2. Updated serve.json, write-manifests.js and @node module per instructions
3. Opened link as follows

https://MyTenant.sharepoint.com/sites/SiteCollection/Lists/List%20A/AllItems.aspx?debugManifestsFile=https://spfx:4321/temp/manifests.js&loadSPFX=true&fieldCustomizers={%22HelloWorld%22:{%22id%22:%225e2385b5-bfd4-44c5-97d6-a392e942a6ab%22,%22properties%22:{%22sampleText%22:%22Value%22}}}

4. Tried updating debugManifestsFile parameter with 0.0.0.0 and localhost with no success
5. Ensured that the field exists as expected

SPFX version: 1.6.0
Docker-SPFX: latest

**Comment by waldekmastykarz** [comment]
Can you navigate in your browser to `https://spfx:4321/temp/manifests.js`?

**Comment by Sartor87** [comment]
Already did that and skipped certificate check.

**Comment by waldekmastykarz** [comment]
Is the component ID mentioned in the URL in the manifests.js file?

**Comment by Sartor87** [comment]
Opened https://spfx:4321/temp/manifests.js
Component ID is not found there

Attached is a link to the solution: https://1drv.ms/u/s!AiJb5ImzKg3U3jJUpAwPWwo4vrQ8?e=cPNUb3

In the same browser I've opened: https://spfx:4321/ and https://localhost:4321/ 
Proceeded to bypass the certificate

To debug, I am accessing

https://tentn.sharepoint.com/sites/siteCollection/Lists/List%20A/AllItems.aspx?debugManifestsFile=https://spfx:4321/temp/manifests.js&loadSPFX=true&fieldCustomizers={%22SPFCustomDialog%22:{%22id%22:%227fb6b701-ff7e-4407-989b-3c37ff532071%22,%22properties%22:{%22sampleText%22:%22Value%22}}}

**Comment by waldekmastykarz** [comment]
If the component ID is not there, it could explain the issue. Have you tried running `gulp clean` and `gulp serve` again?

**Comment by Sartor87** [comment]
Already tried that out, removed by hand

**Comment by Sartor87** [comment]
OK, I've fixed it by re-building the solution from scratch - something was missing somewhere. I'd assume that it has something to do with the component ID as I was playing around it.

**Comment by waldekmastykarz** [comment]
Good to hear you're unblocked 👍
