### ISSUE TITLE
SPFx v1.11.0

### ISSUE THREAD

**Issue by shurick81** [waldekmastykarz/docker-spfx#36]
Should we release a new one?

**Comment by waldekmastykarz** [comment]
Absolutely!

**Comment by shurick81** [comment]
how we do it?

**Comment by waldekmastykarz** [comment]
You can submit a PR or I can push an update myself 😎

**Comment by shurick81** [comment]
I can randomly test it locally but we don't have any tests in this repo to run before submitting the PR?

**Comment by shurick81** [comment]
@waldekmastykarz should we also update the reference of base image to `node:10.22.0`, or what is the best practice in choosing the base image?

**Comment by waldekmastykarz** [comment]
Yes, we could bump the Node image to the latest v10
