### ISSUE TITLE
dependencies not npm installed globally?

### ISSUE THREAD

**Issue by bpkennedy** [waldekmastykarz/docker-spfx#4]
This may be just my understanding Docker (I am just learning about it now).  I would think based on your Dockerfile that these should be globally installed packages after setting up the Docker container:

```
gulp
yo
@microsoft/generator-sharepoint
npm
```

However when I run this command (`npm list -g --depth=0`) to check the globally installed packages I only see this listed:

```
spfx@spfx:/usr/app/spfx$ npm list -g --depth=0
npm info it worked if it ends with ok
npm info using npm@3.10.10
npm info using node@v6.11.3
/usr/local/lib
+-- @microsoft/generator-sharepoint@1.3.2
+-- npm@3.10.10
`-- yo@2.0.0
```

Shouldn't I be seeing gulp there, too?

**Comment by waldekmastykarz** [comment]
It should, but for some reason it isn't listed. Still, you can confirm it is installed by running `gulp -v` in the container command prompt.
