### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by kzimny** [waldekmastykarz/docker-spfx#44]
Great image! Thanks for sharing. I've created a docker image using waldekm/spfx 1.11.0 on Windows 64 Bit. It works great.
Maybe you could pin the link to both [workarounds ](https://github.com/waldekmastykarz/docker-spfx#cant-access-workbench-and-bundles-in-sharepoint-framework-160) on the top of the issues page. That would help to find the solution for all those who can not access the page https://localhost:4321/temp/workbench.html.

**Comment by waldekmastykarz** [comment]
Good tip! Thanks!

**Comment by waldekmastykarz** [comment]
It seems like you can only pin an issue rather than a random link, unless I'm missing something.

**Comment by kzimny** [comment]
Yes, you right. You can pin this issue and mark it as closed. Thanks again!
