### ISSUE TITLE
gulp serve - not work with node 12.21

### ISSUE THREAD

**Issue by Musisimaru** [waldekmastykarz/docker-spfx#47]
Hi, @waldekmastykarz 
i have problem with last tag. Maybe you have a solution.

You have recently updated the version of the image with the node. From 10.22 to 12.21 ([commit](https://github.com/waldekmastykarz/docker-spfx/commit/a48fe8231e2b85f299d68d0ff9d0bda025793fe2#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557)). With this version the command `gulp serve` not work. Error: ` ReferenceError: primordials is not defined`. If i take your image with tag 1.11.0, then everything works as it should.

On the [ms docs site](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment#install-nodejs) they write that the node version should be 10.

**Comment by waldekmastykarz** [comment]
The latest docker image is based on SPFx v1.12 which has some known errors. It's recommended to use SPFx v1.11 until SPFx v1.12.1 is released.
