### ISSUE TITLE
Workaround in SPWebBuildRig.js to access local workbench on Windows no longer works

### ISSUE THREAD

**Issue by Yvand** [waldekmastykarz/docker-spfx#50]
I think it started with @microsoft/generator-sharepoint@1.12.1:
SPWebBuildRig.js changed significantly and I couldn't find how to apply the workaround anymore.

I did a few (unsuccessful) tests:
In node_modules/@microsoft_sp-webpart-workbench/local-workbench/manifests.js, I tried to replace this:
```javascript
manifest.loaderConfig.internalModuleBaseUrls = [manifestsFileUrl];
```
by this:
```javascript
manifest.loaderConfig.internalModuleBaseUrls = ["https://localhost:4321/dist/"];
```
But sadly it has no effect.
I have very little experience with node/npm/bundle, so it's possible I missed something very simple or obvious :)

**Comment by whitegenie** [comment]
I'm having the same problem.
I can't get the workbench to work with version 1.12.1, and the workaround in SPWebBuildRig.js seems to no longer be applicabile
Any updates?

**Comment by MarcoAlfani** [comment]
> I'm having the same problem.
> I can't get the workbench to work with version 1.12.1, and the workaround in SPWebBuildRig.js seems to no longer be applicabile
> Any updates?

I'm having the same problem too; the  object spBuildCoreTasks.writeManifests does not exist anymore.

Can somebody advise?
Thank you

**Comment by waldekmastykarz** [comment]
We've identified the necessary changes to v1.12.0+ here: https://github.com/waldekmastykarz/docker-spfx/issues/54. Could you please check if it works for you?

**Comment by whitegenie** [comment]
It works.
Just one note:
the query string to use to load the scripts in a SP page should be (or, at least, needs to be, to works in my test)
?debug=true&noredir=true&debugManifestsFile=https://**localhost**:4321/temp/manifests.js 
spfx-serve seems to print out:
[spfx-serve] To load your scripts, use this query string: ?debug=true&noredir=true&debugManifestsFile=https://0.0.0.0:4321/temp/manifests.js

To have the right query string printed out by spfx-serve, I had to change the line 108 in node_modules\@microsoft\sp-build-core-tasks\lib\spfxServe\SpfxServeTask.js 
from:
return new url_1.URL(`${taskConfig.https ? 'https' : 'http'}://${taskConfig.hostname}:${taskConfig.port}/`);
to:
return new url_1.URL(`${taskConfig.https ? 'https' : 'http'}://localhost:${taskConfig.port}/`);

Am I the only one encountering this issue?

**Comment by waldekmastykarz** [comment]
@whitegenie are you using the image on Windows or macOS?

**Comment by whitegenie** [comment]
I'm using the image 1.12.1 on Windows 10

**Comment by shurick81** [comment]
@Yvand, @whitegenie, @MarcoAlfani now the instructions for 1.12.1 version are updated in Readme. I guess we could close the issue?

**Comment by Yvand** [comment]
Yep, all good for me
