### ISSUE TITLE
Can't access bundles in SharePoint Framework >=1.12.0 on Windows

### ISSUE THREAD

**Issue by shurick81** [waldekmastykarz/docker-spfx#54]
Starting from the workaround that was suggested for fixing the mapping. `node_modules\@microsoft\sp-build-web\lib\SPWebBuildRig.js` does not contain the lines that were suggested to replace. Hence, we cannot access the bundles.

here's how it was tested in Windows:

1. Run the following lines in PS:

```Powershell
md spfx112testwp02
cd spfx112testwp02
docker run -it --rm -v ${pwd}:/usr/app/spfx waldekm/spfx:1.12.0 yo @microsoft/sharepoint --solution-name helloworld --component-type webpart --component-name wello-world-webpart --component-description "HelloWorld web part" --is-domain-isolated --framework none --environment spo --skip-feature-deployment false
```

2. Agree to provide telemetry
3. After the project is created and modules installed, check `node_modules\@microsoft\sp-build-web\lib\SPWebBuildRig.js` file contents.

**Comment by shurick81** [comment]
Hi, I tested these changes that you suggested with waldekm/spfx:1.13.0 and I managed to add a web part to the SPO hosted workbench! I did not even have to add the `debugBasePath` property to the `config\write-manifests.json`.

**Comment by shurick81** [comment]
Actually, it even worked with just `serve.json` and `WebpackConfigurationGenerator.js` for me in Windows. I'm not sure if modification of `write-manifests.json` and `SpfxServeTask.js` is required for other OSes. Here's a PR: https://github.com/waldekmastykarz/docker-spfx/pull/55

**Comment by waldekmastykarz** [comment]
Thanks for checking!

**Comment by shurick81** [comment]
You are welcome! I forgot to mention that I tested on waldekm/spfx:1.12.1 also, so everything looks good

**Comment by waldekmastykarz** [comment]
Awesome! I appreciate your help 👏
