### ISSUE TITLE
 ENOENT: no such file or directory when trying to run on live SP portal

### ISSUE THREAD

**Issue by Sartor87** [waldekmastykarz/docker-spfx#8]
It is more like a question: is it possible to run the docker container with a live SP portal?

I've managed to run the local workbench, but have troubles running an application customizer.

When I open the default URL:
https://tenant.sharepoint.com/sites/sitecollection/SitePages/Home.aspx?
debugManifestsFile=https%3A%2F%2Fspfx%3A5432%2Ftemp%2Fmanifests.js
&loadSPFX=true
&customActions=%7B%2261049142-3275-4d7f-af7f-01102f143f3c%22%3A%7B%22location%22%3A%22ClientSideExtension.ApplicationCustomizer%22%2C%22properties%22%3A%7B%22testMessage%22%3A%22Test%20message%22%7D%7D%7D

I get the following error:
Error: ENOENT: no such file or directory, stat '/usr/app/spfx/dist/public/temp/manifests.js'

I have registered the localhost in the hosts file.
Tried debugManifestsFile URL to both localhost:4321 and spfx:5432. The local workbench successfully opens at https://localhost:4321

Any guidance on how to run it against live SP portal?

**Comment by Sartor87** [comment]
Thanks, this resolved the problem!

**Comment by waldekmastykarz** [comment]
Excellent! Great to hear it's working 😄
